// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook'

import globals from 'globals'
import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import prettierConfig from 'eslint-config-prettier/flat'

export default defineConfigWithVueTs(
  {
    name: 'app/ignores',
    ignores: [
      '**/dist/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/storybook-static/**',
      // Vendored, regenerated by `npx msw init` — not ours to lint or edit.
      'public/mockServiceWorker.js',
    ],
  },
  { name: 'app/files', files: ['**/*.{ts,mts,tsx,vue,js,mjs}'] },
  { languageOptions: { globals: { ...globals.browser } } },
  js.configs.recommended,
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  {
    name: 'app/vue-rules',
    files: ['**/*.vue'],
    rules: {
      'vue/multi-word-component-names': ['error', { ignores: ['App'] }],
    },
  },
  {
    name: 'app/import-rules',
    // Only src/*: root-level config files (vite.config.ts, ...) sit outside it, where the "@"
    // alias (which maps to "./src/*") can't reach them, so they still import each other by
    // relative path.
    files: ['src/**/*.{ts,mts,tsx,vue}'],
    rules: {
      // Use the "@/..." alias (src/*) instead, including for same-folder siblings: one style
      // everywhere, and imports keep working when a file moves to a different folder.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['./*', '../*'], message: 'Import from "@/..." instead of a relative path.' },
          ],
        },
      ],
    },
  },
  storybook.configs['flat/recommended'],
  // Must stay last: turns off stylistic rules that conflict with Prettier.
  prettierConfig,
)
